AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ArtifactS3Bucket:
    Type: String
    Description: A valid S3 bucket where your application artifact(s) are available for deployment
  ArtifactName:
    Type: String
    Description: The name of your artifact object (e.g. monolith.war)
Resources:
  monolithApplication:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS Elastic Beanstalk Monolith
  monolithApplicationVersion:
    Type: AWS::ElasticBeanstalk::ApplicationVersion
    Properties:
      ApplicationName:
        Ref: monolithApplication
      Description: AWS Elastic Beanstalk Monolith
      SourceBundle:
        S3Bucket:
          Ref: ArtifactS3Bucket
        S3Key:
          Ref: ArtifactName
  applicationConfigurationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName:
        Ref: monolithApplication
      Description: AWS ElasticBeanstalk Application Configuration Template
      OptionSettings:
      - Namespace: aws:autoscaling:asg
        OptionName: MinSize
        Value: '2'
      - Namespace: aws:autoscaling:asg
        OptionName: MaxSize
        Value: '2'
      - Namespace: aws:elasticbeanstalk:environment
        OptionName: EnvironmentType
        Value: LoadBalanced
      SolutionStackName: 64bit Amazon Linux 2018.03 v3.0.1 running Tomcat 8.5 Java 8
  applicationEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName:
        Ref: monolithApplication
      Description: AWS ElasticBeanstalk Monolith
      TemplateName:
        Ref: applicationConfigurationTemplate
      VersionLabel:
        Ref: monolithApplicationVersion
